### ISSUE TITLE
macOS Ventura Latitude 5300

### ISSUE THREAD

**Issue by cvega48** [ahianf/dell-latitude-5300-hackintosh#3]
By any chance would you happen to have tried getting Ventura on your Setup? 
I have an 5300 and running latest Monterey version 12.6
![image](https://user-images.githubusercontent.com/55467816/197630469-3572329c-2e86-4d0b-99a8-29afd7cf1a4e.png)
Please let me know.

**Comment by durujavi** [comment]
Hola, ¿me podrías ayudar con Monterey y un Latitude 5300? Muchas gracias.

**Comment by cvega48** [comment]
> Hola, ¿me podrías ayudar con Monterey y un Latitude 5300? Muchas gracias.

Sorry la maquina que tengo es una Latitude 5400. No se si te funcione igual con el EFI que tengo.

**Comment by durujavi** [comment]
¿No te importaría ayudarme con el 5400? Estoy viéndolo y es la misma maquina, con la misma generación de procesador. Gracias!

**Comment by cvega48** [comment]
Use este EFI y me funciona todo super bien. Incluso el SD Card Reader:

**https://github.com/Dugganclock/Dell-Latitude-5400-Hackintosh-OpenCore**
